### ISSUE TITLE
Run code validation checks with pre-commit

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#974]
**Is your feature request related to a problem? Please describe.**
We should run the same or more code validation tools that our Travis runs using https://pre-commit.com/.

**Describe the solution you'd like**
Pre-commit tool should run a local validation script and verify that new commit doesn't break UT's, doesn't introduce new flake8 warnings etc.

**Describe alternatives you've considered**
Using git-hooks

- [x] Add config for pre-commit. (0d) - @mssalvatore 
- [x] Add pre-commit hook for black. Ensure travis CI uses the same version. (0d) - @mssalvatore 
- [x] Add pre-commit hook for flake8. Ensure travis CI uses the same version. (0d) - @mssalvatore 
- [x] Add pre-commit hook for isort. Ensure travis CI uses the same version. (0d) - @mssalvatore 
- [x] Alter linux deployment script to install and run pre-commit. (0d) - @mssalvatore 
- [x] Alter windows deployment script to install and run pre-commit (0.25d) - @VakarisZ 
- [x] Update dev documentation to include instructions about pre-commit and a warning that CI will reject non-compliant code. (0d) - @mssalvatore

**Comment by mssalvatore** [comment]
I've had good luck with these hooks in the past:

```
repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
        - id: isort

  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
```

The version numbers are probably out of date.

We probably want to run `black` against all of the python code before installing pre-commit. Otherwise, it will reformat the files you've changed that are not already properly formatted before each commit and potentially make your commits more confusing.
